name: Linter
on: [ pull_request ]
jobs:
  dclint:
    name: runner / dclint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - uses: docker-compose-linter/dclint-github-action@v1.6.0
        with:
          path: ./
          recursive: true
